### ISSUE TITLE
Screen Orientation

### ISSUE THREAD

**Issue by hinddeep** [capacitor-community/proposals#59] opened 2020-08-26 17:13 UTC
## Plugin Request

**Name**: Screen Orientation
**Package**: `@capacitor-community/screen-orientation`

### Platform(s)

Android,
iOS,
Web/PWA

### Existing Solutions

https://ionicframework.com/docs/native/screen-orientation
https://github.com/hinddeep/capacitor-screen-orientation

### Description

I ported the existing Cordova Screen Orientation plugin to Capacitor. The iOS portion of the plugin has been written in Swift as opposed to super difficult Objective-C in the case of its Cordova brethren. This makes it super easy to edit if needed. The plugin supports Android, iOS and Web/PWA. Supported functions:
1) Get the current screen orientation
2) Lock the screen to the specified orientation
3) Unlock screen orientation
4) Listen to screen orientation changes - and then perform any necessary action(s)
5) Rotate the screen to the specified orientation

**Comment by imhoffd** [comment] 2020-08-27 05:11
Duplicate of https://github.com/capacitor-community/proposals/issues/8

**Closed as completed by imhoffd** 2020-08-27 05:11 UTC
Labels: plugin proposal
